apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-express-api-depl
  labels:
    app: gitops-express-api-depl
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-express-api
  template:
    metadata:
      labels:
        app: gitops-express-api
    spec:
      containers:
        - name: gitops-express-api-container
          image: asd2321s2/gitops-express-api:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
