apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
images:
  - name: asd2321s2/gitops-express-api
    newName: df9d7aef79c18b51d73e142f5c05d9fcf08fdd3d
