apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: asd2321s2/gitops-express-api
  newName: 8b94cfbd29790c2d6b93b609f5e6083a47ac91b7
