apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: asd2321s2/gitops-express-api
  newName: 6a7d4f51cdb525c279730a7871124f4b46432a1b
