name: Deploy to Minikube

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t asd2321s2/gitops-express-api:$IMAGE_TAG .
          docker tag asd2321s2/gitops-express-api:$IMAGE_TAG asd2321s2/gitops-express-api:latest

      - name: Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Pushing image with tag: $IMAGE_TAG"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push asd2321s2/gitops-express-api:$IMAGE_TAG
          docker push asd2321s2/gitops-express-api:latest

      - name: Update Kustomize Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: asd2321s2/express-api:.*|image: asd2321s2/express-api:$IMAGE_TAG|" k8s/overlays/${{ github.ref_name }}/deployment-patch.yaml
          else
            sed -i "s|image: asd2321s2/express-api:.*|image: asd2321s2/express-api:$IMAGE_TAG|" k8s/overlays/${{ github.ref_name }}/deployment-patch.yaml
          fi
          git add k8s/overlays/${{ github.ref_name }}/deployment-patch.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin ${{ github.ref_name }}
