name: Deploy to Minikube

on:
  push:
    branches:
      - develop
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t asd2321s2/gitops-express-api:$IMAGE_TAG .
          docker tag asd2321s2/gitops-express-api:$IMAGE_TAG asd2321s2/gitops-express-api:v1.0.${{ github.run_number }}
          docker push asd2321s2/gitops-express-api:$IMAGE_TAG
          docker push asd2321s2/gitops-express-api:v1.0.${{ github.run_number }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --grpc-web

      - name: Deploy with ArgoCD
        run: |
          APP_NAME="gitops-express-api-dev"
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            APP_NAME="gitops-express-api-prod"
          fi
          IMAGE_TAG=${{ github.sha }}
          argocd app set $APP_NAME --image asd2321s2/gitops-express-api:$IMAGE_TAG
          argocd app sync $APP_NAME
          argocd app wait $APP_NAME --health --sync
