name: Deploy to Minikube

on:
  push:
    branches:
      - develop
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t asd2321s2/gitops-express-api:$IMAGE_TAG .
          docker tag asd2321s2/gitops-express-api:$IMAGE_TAG asd2321s2/gitops-express-api:v1.0.${{ github.run_number }}
          docker push asd2321s2/gitops-express-api:$IMAGE_TAG
          docker push asd2321s2/gitops-express-api:v1.0.${{ github.run_number }}

  deploy:
    needs: build
    runs-on: self-hosted
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply Service Account and Role Binding
        run: |
          kubectl apply -f k8s/argocd/rbac/gitops-express-api-sa.yaml
          kubectl apply -f k8s/argocd/rbac/gitops-express-api-cluster-role-binding.yaml
          kubectl apply -f k8s/argocd/rbac/gitops-express-api-cm.yaml

      - name: Generate ArgoCD Auth Token
        id: generate_token
        run: |
          TOKEN=$(kubectl -n argocd create token argocd-admin)
          echo "::add-mask::$TOKEN"
          echo "ARGOCD_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Update Kustomize Image Tag
        run: |
          IMAGE_TAG=${{ github.sha }}
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            cd k8s/overlays/prod
            kustomize edit set image asd2321s2/gitops-express-api=$IMAGE_TAG
          else
            cd k8s/overlays/dev
            kustomize edit set image asd2321s2/gitops-express-api=$IMAGE_TAG
          fi

      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --auth-token ${{ env.ARGOCD_AUTH_TOKEN }} \
            --insecure

      # - name: Login to ArgoCD
      #   run: |
      #     argocd login ${{ secrets.ARGOCD_SERVER }} \
      #       --username ${{ secrets.ARGOCD_USERNAME }} \
      #       --password ${{ secrets.ARGOCD_PASSWORD }} \
      #       --insecure

      - name: Sync Application with ArgoCD
        run: |
          APP_NAME="gitops-express-api-dev"
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            APP_NAME="gitops-express-api-prod"
          fi
          argocd app sync gitops-express-api-rbac-app
          # argocd app sync $APP_NAME
          # argocd app wait $APP_NAME --health --sync
